import streamlit as st
st.set_page_config (page_title="My Webpage", layout="wide")

col1, col2, col3, col4, col5 = st.columns (5)
with col1:
    st.title("Hallo")
    st.subheader("This is Dosun.")
with col2:
    st.empty()
with col3:
    st.empty()
with col4:
    st.empty()
with col5:
    st.write("[Instagram](https://instagram.com/fznnadt?igshid=YmMyMTA2M2Y=)")

st.write ("Hallo semuanya. Perkenalkan nama saya dosun. Ini adalah webpage pertama saya. Terima kasih sudah membuka webpage ini. Saat ini masih kosong. Nanti isinya bakal menarik, lho.")
st.text ("Nantikan yaa!. See you.")
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text (''' ''')
st.text ("*masih dalam perkembangan")
